# Generated by Django 2.2 on 2020-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('D', 'Dell'), ('L', 'Lenovo'), ('A', 'Acer'), ('AP', 'Apple'), ('HP', 'HP')], max_length=2),
        ),
    ]
